#!/bin/bash

cp ./src/.libs/* ./file-tests
cd file-tests
echo -n "Will compare against database generated by file-"
cat current_db_hash.txt
export TZ="Europe/Prague"
LD_LIBRARY_PATH=. python ./fast-regression-test.py "./lt-file -m ../magic/magic.mgc" exact
ret=$?
cd ..

exit $ret
